name: Daily Data Update and Deploy

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 1:00 (約台灣時間 9:00) 運行
  workflow_dispatch:  # 允許手動觸發

permissions:
  contents: write
  pages: write

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas

    - name: Update stock data
      run: python update_data.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push if changed
      run: |
        git add stock_data/*.json
        git diff --staged --quiet || (git commit -m "chore: 更新股票數據 [skip ci]" && git push)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        force_orphan: true 