name: 更新股票數據

on:
  schedule:
    - cron: '0 0 * * 0'  # 每週日執行
  workflow_dispatch:  # 允許手動觸發

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 設定 Python 環境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安裝依賴套件
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas
    
    - name: 更新股票數據
      run: python update_data.py
    
    - name: 提交更新
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add data.json
        git commit -m "更新股票數據 $(date +'%Y-%m-%d')"
        git push 